#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonWidgetInputExtended

#include "Basic.hpp"

#include "CommonWidgetInputExtended_classes.hpp"
#include "CommonWidgetInputExtended_parameters.hpp"


namespace SDK
{

// Function CommonWidgetInputExtended.CommonActivatableWidgetInputExtended.ShouldAllowBackAction
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UCommonActivatableWidgetInputExtended::ShouldAllowBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CommonActivatableWidgetInputExtended", "ShouldAllowBackAction");

	Params::CommonActivatableWidgetInputExtended_ShouldAllowBackAction Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

