#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommonWidgetInputExtended

#include "Basic.hpp"


namespace SDK::Params
{

// Function CommonWidgetInputExtended.CommonActivatableWidgetInputExtended.ShouldAllowBackAction
// 0x0001 (0x0001 - 0x0000)
struct CommonActivatableWidgetInputExtended_ShouldAllowBackAction final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(CommonActivatableWidgetInputExtended_ShouldAllowBackAction) == 0x000001, "Wrong alignment on CommonActivatableWidgetInputExtended_ShouldAllowBackAction");
static_assert(sizeof(CommonActivatableWidgetInputExtended_ShouldAllowBackAction) == 0x000001, "Wrong size on CommonActivatableWidgetInputExtended_ShouldAllowBackAction");
static_assert(offsetof(CommonActivatableWidgetInputExtended_ShouldAllowBackAction, ReturnValue) == 0x000000, "Member 'CommonActivatableWidgetInputExtended_ShouldAllowBackAction::ReturnValue' has a wrong offset!");

}

