#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S6ABTests

#include "Basic.hpp"

#include "S6ABTests_classes.hpp"
#include "S6ABTests_parameters.hpp"


namespace SDK
{

// Function S6ABTests.S6ABTestClientServerSyncer.RpcServer_SendToServer
// (Final, Net, NetReliable, Native, Event, Private, NetServer)
// Parameters:
// TArray<struct FABTestAssignment>        TestAssignments                                        (ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void US6ABTestClientServerSyncer::RpcServer_SendToServer(const TArray<struct FABTestAssignment>& TestAssignments)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("S6ABTestClientServerSyncer", "RpcServer_SendToServer");

	Params::S6ABTestClientServerSyncer_RpcServer_SendToServer Parms{};

	Parms.TestAssignments = std::move(TestAssignments);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function S6ABTests.S6ABTestManager.HandleAbTestSettingsChanged
// (Final, Native, Private)
// Parameters:
// class US6ABTestSettings*                Settings                                               (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void US6ABTestManager::HandleAbTestSettingsChanged(const class US6ABTestSettings* Settings)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("S6ABTestManager", "HandleAbTestSettingsChanged");

	Params::S6ABTestManager_HandleAbTestSettingsChanged Parms{};

	Parms.Settings = Settings;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function S6ABTests.S6ABTestManager.HandlePlayerControllerDestroyed
// (Final, Native, Private)
// Parameters:
// class AActor*                           Actor                                                  (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void US6ABTestManager::HandlePlayerControllerDestroyed(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("S6ABTestManager", "HandlePlayerControllerDestroyed");

	Params::S6ABTestManager_HandlePlayerControllerDestroyed Parms{};

	Parms.Actor = Actor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function S6ABTests.S6ABTestManager.Client_GetValueOfAbTest
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class US6ABTest*                        AbTest                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int64 US6ABTestManager::Client_GetValueOfAbTest(const class US6ABTest* AbTest) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("S6ABTestManager", "Client_GetValueOfAbTest");

	Params::S6ABTestManager_Client_GetValueOfAbTest Parms{};

	Parms.AbTest = AbTest;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function S6ABTests.S6ABTestManager.IsEnabled
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool US6ABTestManager::IsEnabled() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("S6ABTestManager", "IsEnabled");

	Params::S6ABTestManager_IsEnabled Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function S6ABTests.S6ABTestManager.Server_GetValueOfAbTest
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class US6ABTest*                        AbTest                                                 (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class APlayerController*                PC                                                     (ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int64                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int64 US6ABTestManager::Server_GetValueOfAbTest(const class US6ABTest* AbTest, const class APlayerController* PC) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("S6ABTestManager", "Server_GetValueOfAbTest");

	Params::S6ABTestManager_Server_GetValueOfAbTest Parms{};

	Parms.AbTest = AbTest;
	Parms.PC = PC;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

