#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ValeriaDTOs

#include "Basic.hpp"

#include "ValeriaDTOs_structs.hpp"


namespace SDK::Params
{

// Function ValeriaDTOs.VALDTOS_MetaCharacterCustomizationFuncLib.CharacterCreationOptions_EqualEqual
// 0x03F8 (0x03F8 - 0x0000)
struct VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual final
{
public:
	struct FVALDTOS_CharacterCustomizationLoadout_PersistDTO_Stable A;                                                 // 0x0000(0x01F8)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FVALDTOS_CharacterCustomizationLoadout_PersistDTO_Stable B;                                                 // 0x01F8(0x01F8)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x03F0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A86[0x7];                                     // 0x03F1(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual) == 0x000008, "Wrong alignment on VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual");
static_assert(sizeof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual) == 0x0003F8, "Wrong size on VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual, A) == 0x000000, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual::A' has a wrong offset!");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual, B) == 0x0001F8, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual::B' has a wrong offset!");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual, ReturnValue) == 0x0003F0, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCreationOptions_EqualEqual::ReturnValue' has a wrong offset!");

// Function ValeriaDTOs.VALDTOS_MetaCharacterCustomizationFuncLib.CharacterCustomizationOptions_EqualEqual
// 0x0FC8 (0x0FC8 - 0x0000)
struct VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual final
{
public:
	struct FVALDTOS_CharacterCustomizationLoadout_PersistDTO_Volatile A;                                                 // 0x0000(0x07E0)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FVALDTOS_CharacterCustomizationLoadout_PersistDTO_Volatile B;                                                 // 0x07E0(0x07E0)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0FC0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A87[0x7];                                     // 0x0FC1(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual) == 0x000008, "Wrong alignment on VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual");
static_assert(sizeof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual) == 0x000FC8, "Wrong size on VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual, A) == 0x000000, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual::A' has a wrong offset!");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual, B) == 0x0007E0, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual::B' has a wrong offset!");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual, ReturnValue) == 0x000FC0, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_CharacterCustomizationOptions_EqualEqual::ReturnValue' has a wrong offset!");

// Function ValeriaDTOs.VALDTOS_MetaCharacterCustomizationFuncLib.MetaCharacterFormat_EqualEqual
// 0x1458 (0x1458 - 0x0000)
struct VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual final
{
public:
	struct FVALDTOS_MetaCharacterFormat           A;                                                 // 0x0000(0x0A28)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FVALDTOS_MetaCharacterFormat           B;                                                 // 0x0A28(0x0A28)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x1450(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1A88[0x7];                                     // 0x1451(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual) == 0x000008, "Wrong alignment on VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual");
static_assert(sizeof(VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual) == 0x001458, "Wrong size on VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual, A) == 0x000000, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual::A' has a wrong offset!");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual, B) == 0x000A28, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual::B' has a wrong offset!");
static_assert(offsetof(VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual, ReturnValue) == 0x001450, "Member 'VALDTOS_MetaCharacterCustomizationFuncLib_MetaCharacterFormat_EqualEqual::ReturnValue' has a wrong offset!");

}

